### ISSUE TITLE
Removing mocks

### ISSUE THREAD

**Issue by divergentdave** [poetic/nock-vcr-recorder#8]
I would like to combine tests using cassettes with tests using real HTTP requests in the same test suite. It appears that there isn't a good way to do this presently, because nock responses are only ever removed or cleared when adding new nock responses. If the nockReset() function were exposed as a public API, that would suffice.

**Comment by leonidez** [comment]
Fixed with #9

**Comment by divergentdave** [comment]
Great, thank you!
